name: workout_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  google_sign_in: ^6.1.5
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  supabase_flutter: ^2.5.1
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.4
  permission_handler: ^11.3.1
  video_player: ^2.8.6
  confetti: ^0.8.0
  # Localization
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true                # for localization
  uses-material-design: true
  assets:
    - assets/images/fatloss2.jpg
    - assets/images/muscle_builder.jpg
    - assets/images/cardio.jpg
    - assets/images/
    - assets/images/meals/
    - assets/videos/workouts/